### ISSUE TITLE
Action does not work with `pull_request` events

### ISSUE THREAD

**Issue by skearnes** [trsvchn/colab-badge-action#3]
The `pull_request` workflow event uses a different value for `GITHUB_REF` that does not include the branch name (in contrast to the `push` event); instead, it includes information about the PR, e.g. `refs/pull/72/merge`. This causes `git push` to fail with errors like this:

```
! [remote rejected] HEAD -> refs/pull/72/merge (deny updating a hidden ref)
```

**Comment by trsvchn** [comment]
I am new to github actions, maybe we can use different configs for each event:

[Example using multiple events with activity types or configuration](https://help.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration)

**Comment by tarasio-mirror** [comment]
I was able to reproduce an issue.
And figured out that in addition to `GITHUB_REF` there are some addition env vars: `GITHUB_HEAD_REF`, `GITHUB_BASE_REF`. And they have diff values on pushes and PRs:

on push:

```bash
DEBUG: GITHUB_HEAD_REF: 
DEBUG: GITHUB_BASE_REF: 
DEBUG: GITHUB_REF: refs/heads/pr-test2
DEBUG: INPUT_TARGET_BRANCH: 
DEBUG: BRANCH: pr-test2
```

on PR:

```bash
DEBUG: GITHUB_HEAD_REF: pr-test2
DEBUG: GITHUB_BASE_REF: master
DEBUG: GITHUB_REF: refs/pull/2/merge
DEBUG: INPUT_TARGET_BRANCH: 
DEBUG: BRANCH: merge
```

As you can see it causes some problems with branch name and later with pushing step.
I think now we can use this info to fix this issue

**Comment by tarasio-mirror** [comment]
It seems to work now: trsvchn/colab-badge-action-test/pull/9
I am new to github actions so, I used these resources to solve a problem.

- [Fix a Git detached head?](https://stackoverflow.com/a/10229202/10749432) 
- [HTTP-based Git access by an installation](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation)
- [Push to origin from GitHub action](https://stackoverflow.com/a/58393457/10749432)
- [Making pull requests to a GitHub repository automatically with GitHub Actions](https://stackoverflow.com/q/57503578/10749432)
- [GitHub Actions: How to Automate Code Formatting in Pull Requests](https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/)

**Comment by skearnes** [comment]
Thanks for digging into that!

**Comment by tarasio-mirror** [comment]
> Thanks for digging into that!

Quarantine gives me too much free time at home)
